### PR TITLE
chore: Refresh translations from Transifex

### PR DESCRIPTION
**Pull request by thephez**
This includes some fresh translation work that came in after I uploaded the new stuff to Transifex (fr). As well as the changes in the 18.0.0 branch.

### CODE REVIEW

**Review by UdjinM6 — APPROVED** [review]
🤷‍♂️

**Comment by thephez** [comment]
> :man_shrugging: 

I just try to do what @strophy showed me last year. So far I don't think I've broken it :crossed_fingers: :smile:

**Review by strophy — APPROVED** [review]
🤷‍♂️

**Comment by thephez** [comment]
The confidence is so inspiring! :joy: I'll sum up with this:

image

**Pull request merged**
