### PR TITLE
chore: 0.17.0.3 update

### PR DESCRIPTION
**Pull request by thephez**
Change download links to point to the newest version

### CODE REVIEW

**Review by strophy — APPROVED** [review]
LGTM, can you do the same for Electrum binary download links? Same or different PR, doesn't matter I guess.

**Comment by thephez** [comment]
@strophy Updated the Electrum links too and now need a re-review

**Review by strophy — APPROVED** [review]
:+1:

**Comment by thephez** [comment]
@strophy One more time please :pray: :slightly_smiling_face:

**Review by strophy — APPROVED** [review]
LGTM

**Pull request merged**
