### PR TITLE
docs: update circa 2019 recommended specs

### PR DESCRIPTION
**Pull request by thephez**
Masternode hardware recommendations haven't been modified since 2019. Update to some reasonable values.
https://dash-docs--205.org.readthedocs.build/en/205/docs/user/masternodes/understanding.html#masternode-requirements

### CODE REVIEW

**Review by UdjinM6 — APPROVED** [review]
LGTM

**Comment by strophy** [comment]
The values for disk and CPU look good, but RAM and network seem unnecessarily high to me, particularly since a memory leak in core was recently fixed. We are actually scaling down our instance size on AWS to only 2GB RAM + swap for testnet as a result. RAM usage for a mainnet masternode is steady at around 1GB after 5 weeks uptime on Core 18.2.1, and network usage is also < 100 GB/month, far below the 2 TB you are suggesting here. Do you guys think requirements will increase in the near future or what is the increase here based on?

We should consider adding a separate table with higher specs for HPMN though.

**Comment by thephez** [comment]
> The values for disk and CPU look good, but RAM and network seem unnecessarily high to me, particularly since a memory leak in core was recently fixed. We are actually scaling down our instance size on AWS to only 2GB RAM + swap for testnet as a result. RAM usage for a mainnet masternode is steady at around 1GB after 5 weeks uptime on Core 18.2.1, and network usage is also < 100 GB/month, far below the 2 TB you are suggesting here. Do you guys think requirements will increase in the near future or what is the increase here based on?
> 
> We should consider adding a separate table with higher specs for HPMN though.

The network usage was based on some info from a MN hosting service indicating ~1 TB wasn't uncommon, but pertussis I misunderstood something if you see an order of magnitude lower 🤔.

Also in talking to both a developer and a hosting provider, the 8GB recommendation came up (independently) with the hosting provider indicating that is what they use. 

The minimum column here isn't necessarily indicating what one can "get away with", but a base that is hopefully able to handle cases like situation earlier this year that resulted in a number of pose scores /bans higher than we'd hope for.

I'll leave this open for now and see if we get any more stats / corrections.

**Comment by thephez** [comment]
I put the bandwidth values back to where they were originally since it seems they were fine. Not sure what to do with the RAM requirements. :thinking:

**Comment by thephez** [comment]
Decided to merge as-is. We will be revisiting soon anyway to add HPMN info.

**Pull request merged**
