### PR TITLE
deleted pages with the file name.

### PR DESCRIPTION
**Pull request by rmdash**

### CODE REVIEW

**Review by thephez — CHANGES_REQUESTED** [review]
Please also remove the reference to the v016-upgrade.rst in the `.../developers/index.rst` file. This will eliminate a warning when building:

image

**Comment by rmdash** [comment]
Done.

**Review by thephez — CHANGES_REQUESTED** [review]
Oh, one more thing I always forget - we need to delete the reference to the removed file from the transifex config too. You can find that here: https://github.com/dashpay/docs/blob/18.0.0/.tx/config#L70-L75

**Review by thephez — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
