### PR TITLE
docs: update Android wallet recovery info

### PR DESCRIPTION
**Pull request by thephez**
Based on #110 
Preview: https://dash-docs--113.org.readthedocs.build/en/113/wallets/recovery.html#dash-android

### CODE REVIEW

**Comment by thephez** [comment]
@strophy These pngs seem huge. Do you have some way of making them smaller?

**Comment by thephez** [comment]
@hashengineering Could you take a look at this as well? The preview link in the PR description will allow you to see what the change will look like.

**Comment by strophy** [comment]
> 
> 
> @strophy These pngs seem huge. Do you have some way of making them smaller?

These images contain photos, so saving in a lossless image format like PNG will result in large files. You can just re-save them as JPG. Can we use consistent image dimensions as well?

**Comment by thephez** [comment]
Updated with suggested changes

**Review by strophy — APPROVED** [review]
LGTM! :1st_place_medal:

**Pull request merged**
